# Generated by Django 5.0.14 on 2026-07-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_year', models.CharField(blank=True, max_length=8)),
                ('params_json', models.JSONField(blank=True, default=dict)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeshSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity_cm_per_year', models.FloatField(blank=True, null=True)),
                ('land_use_class', models.CharField(blank=True, max_length=64)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('road_length_m', models.FloatField(blank=True, null=True)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('sewer_event_count', models.PositiveIntegerField(default=0)),
                ('mesh_cell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_summary', to='core.meshcell')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesh_summaries', to='analysis.analysisrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run'], name='analysis_me_run_id_030f2c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='meshsummary',
            constraint=models.UniqueConstraint(fields=('mesh_cell', 'run'), name='unique_mesh_summary_per_run'),
        ),
    ]
