# Generated by Django 5.0.14 on 2026-07-20 21:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeshCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh_code', models.CharField(max_length=32, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=6668)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=6668)),
            ],
            options={
                'indexes': [models.Index(fields=['mesh_code'], name='core_meshce_mesh_co_531ccb_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroundClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geology_class', models.CharField(blank=True, max_length=64)),
                ('ground_classification', models.CharField(blank=True, max_length=64)),
                ('land_use_class', models.CharField(blank=True, max_length=64)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('source_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mesh_cell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ground_class', to='core.meshcell')),
            ],
        ),
        migrations.CreateModel(
            name='PrecipitationObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('accumulated_mm', models.FloatField()),
                ('source', models.CharField(max_length=64)),
                ('mesh_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precipitation_observations', to='core.meshcell')),
            ],
            options={
                'ordering': ['mesh_cell_id', 'period_start'],
            },
        ),
        migrations.CreateModel(
            name='RoadExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_length_m', models.FloatField()),
                ('source', models.CharField(default='osm', max_length=64)),
                ('mesh_cell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='road_exposure', to='core.meshcell')),
            ],
        ),
        migrations.CreateModel(
            name='SubsidenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=6668)),
                ('fiscal_year', models.CharField(blank=True, max_length=8)),
                ('prefecture', models.CharField(blank=True, max_length=32)),
                ('location_text', models.CharField(max_length=255)),
                ('road_name', models.CharField(blank=True, max_length=128)),
                ('road_administrator', models.CharField(blank=True, max_length=64)),
                ('road_jurisdiction', models.CharField(blank=True, max_length=16)),
                ('cause_facility', models.CharField(blank=True, max_length=64)),
                ('depth_m', models.FloatField(blank=True, null=True)),
                ('geocode_confidence', models.CharField(blank=True, max_length=16)),
                ('source', models.CharField(default='mlit_kanbotsu', max_length=64)),
                ('mesh_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidence_events', to='core.meshcell')),
            ],
        ),
        migrations.CreateModel(
            name='DisplacementVelocity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=8)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('velocity_cm_per_year', models.FloatField()),
                ('source', models.CharField(default='gsi_sar_tsa', max_length=64)),
                ('mesh_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displacement_velocities', to='core.meshcell')),
            ],
            options={
                'ordering': ['mesh_cell_id', 'fiscal_year'],
                'indexes': [models.Index(fields=['mesh_cell', 'fiscal_year'], name='core_displa_mesh_ce_383b25_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='displacementvelocity',
            constraint=models.UniqueConstraint(fields=('mesh_cell', 'fiscal_year', 'source'), name='unique_displacement_velocity'),
        ),
        migrations.AddIndex(
            model_name='precipitationobservation',
            index=models.Index(fields=['mesh_cell', 'period_start', 'period_end'], name='core_precip_mesh_ce_65fa6a_idx'),
        ),
        migrations.AddIndex(
            model_name='subsidenceevent',
            index=models.Index(fields=['mesh_cell'], name='core_subsid_mesh_ce_d3da73_idx'),
        ),
    ]
