# Generated by Django 5.0.14 on 2026-07-21 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplacementAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_sha256', models.CharField(max_length=64, unique=True)),
                ('retrieved_at', models.DateTimeField()),
                ('fiscal_year', models.CharField(max_length=8)),
                ('fiscal_year_provenance', models.CharField(max_length=32)),
                ('api_file_name', models.CharField(blank=True, max_length=255)),
                ('zip_path', models.CharField(blank=True, max_length=255)),
                ('tif_name', models.CharField(blank=True, max_length=255)),
                ('bbox', models.JSONField()),
                ('raw_file_info', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='gsi_sar_tsa', max_length=64)),
            ],
            options={
                'ordering': ['-retrieved_at'],
            },
        ),
        migrations.AddField(
            model_name='displacementvelocity',
            name='acquisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='velocities', to='core.displacementacquisition'),
        ),
    ]
