# Generated by Django 5.0.14 on 2026-07-21 21:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seed', models.PositiveIntegerField()),
                ('params_json', models.JSONField(blank=True, default=dict)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyntheticPipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=6668)),
                ('osm_way_id', models.BigIntegerField(blank=True, help_text='配置元のOSM way ID(由来追跡用。架空属性ではない)', null=True)),
                ('seed', models.PositiveIntegerField(help_text='決定的生成に使った乱数シード')),
                ('install_year', models.PositiveSmallIntegerField(help_text='架空の布設年(Illustrative)')),
                ('pipe_material', models.CharField(choices=[('illustrative_concrete', 'ヒューム管(例示)'), ('illustrative_ceramic', '陶管(例示)'), ('illustrative_pvc', '塩ビ管(例示)'), ('illustrative_steel', '鋼管(例示)')], help_text='架空の管種(Illustrative)', max_length=32)),
                ('is_synthetic', models.BooleanField(default=True, editable=False)),
                ('mesh_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthetic_pipes', to='core.meshcell')),
            ],
            options={
                'indexes': [models.Index(fields=['mesh_cell'], name='triage_synt_mesh_ce_bd2456_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeshPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_index', models.FloatField()),
                ('tier', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=8)),
                ('velocity_cm_per_year', models.FloatField(blank=True, null=True)),
                ('road_length_m', models.FloatField(blank=True, null=True)),
                ('sewer_event_count', models.PositiveIntegerField(default=0)),
                ('pipe_count', models.PositiveIntegerField(default=0)),
                ('mesh_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_priorities', to='core.meshcell')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesh_priorities', to='triage.triagerun')),
            ],
            options={
                'indexes': [models.Index(fields=['run'], name='triage_mesh_run_id_bc8798_idx'), models.Index(fields=['tier'], name='triage_mesh_tier_23ece5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='meshpriority',
            constraint=models.UniqueConstraint(fields=('mesh_cell', 'run'), name='unique_mesh_priority_per_run'),
        ),
    ]
